In [1]:
import numpy as np

from sklearn.datasets import make_regression

In [ ]:
def Perceptron_Regressor(self):
    def __init__(self, 
                 random_state=None,
                 cost_function='MSE',
                 gradient_descent='batch')
        
        self.random_state = random_state
        self.cost_function = cost_function
        
        
        
        assert self.gradient_descent.lower() in ['stocastic', 'batch'], (
            f'Expected value for gradient_descent: "stocastic" or "batch". '
            f'Got: "{gradient_descent}"'
        
        
        assert self.gradient_descent.lower() in ['stocastic', 'batch'], (
            f'Expected value for gradient_descent: "stocastic" or "batch". '
            f'Got: "{gradient_descent}"'
        )
        
        
        
        

        
    def fit(self, X, Y, learning_rate=0.01, epochs=20, 
            initialize=True, \
            gradient_descent='batch',
            cost_function='MSE
           
           ):

        self.X = X
        self.Y = Y
        self.alpha = alpha
        self.epochs = epochs
        self.initialize = initialize
        self.gradient_descent = gradient_descent
        
        
        
        if self.initialize:
            # Random numbers generator with given random state
            rgen = np.random.RandomState(seed=self.random_state)
            self.w = rgen.normal(loc=0.0,    # Mean (“centre”) of the distribution.
                                 scale=0.5,  # Standard deviation
                                 size=self.X.shape[1])
            self.b = np.float(0.)
        
        if gradient_descent = 'batch':
            pass
        
        if gradient_descent = 'stocastic':
        
        

In [30]:
rgen = np.random.RandomState(seed=None)
rgen.normal(loc= 0.0, scale=0.5, size=10)


array([ 0.19513438, -0.16810061,  0.07847264,  0.09157491,  0.00512991,
       -0.20091552,  0.24832677, -0.21095941, -1.17163336, -0.18641637])

In [23]:
np.random.normal(size=10)

array([-0.85997771,  0.92726672, -0.25084082, -0.1672017 , -0.44774749,
       -0.39547081, -0.73719239, -1.93334004,  1.14931168,  1.00351464])

In [6]:
np.random.rand(random_)

array([0.39141906, 0.05291873, 0.25141754, 0.7219887 , 0.30420502,
       0.43998737, 0.78522769, 0.06600296, 0.57640781, 0.7197574 ])

In [21]:
X, Y = make_regression(n_samples=1000, 
                                n_features=100,
                                n_targets=1,
                                noise=0)

In [22]:
X.shape, Y.shape, type(X), type(Y)

((1000, 100), (1000,), numpy.ndarray, numpy.ndarray)